import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1772892052552 implements MigrationInterface {
    name = 'InitialSchema1772892052552'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."center_meeting_dates_week_enum" AS ENUM('1', '2', '3', '4')`);
        await queryRunner.query(`CREATE TYPE "public"."center_meeting_dates_day_enum" AS ENUM('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday')`);
        await queryRunner.query(`CREATE TABLE "center_meeting_dates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "week" "public"."center_meeting_dates_week_enum" NOT NULL, "day" "public"."center_meeting_dates_day_enum" NOT NULL, CONSTRAINT "PK_cde0b4ee6e892adc1c58511d1ee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "UQ_037e43ea842b18ce4e5f4dcfd06" UNIQUE ("name"), CONSTRAINT "PK_2fd3770acdb67736f1a3e3d5399" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "groups" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "system_name" character varying NOT NULL, "name" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "staff_name" character varying NOT NULL, "audit_data" jsonb NOT NULL, "timeline" jsonb NOT NULL, "office_name" character varying NOT NULL, "status_id" uuid NOT NULL, "group_leader_id" uuid NOT NULL, "staff_id" uuid NOT NULL, "created_by_id" uuid NOT NULL, "center_id" uuid NOT NULL, CONSTRAINT "REL_697c73a750a4c53f80a37cafa3" UNIQUE ("group_leader_id"), CONSTRAINT "PK_659d1483316afb28afd3a90646e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "center" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "center_code" character varying NOT NULL, "user" uuid NOT NULL, "staff_name" character varying NOT NULL, "office" uuid NOT NULL, "office_name" character varying NOT NULL, "created_by" TIMESTAMP NOT NULL, "meeting_time" TIME, "location" jsonb, "center_leadership" jsonb, "meetingDateId" uuid NOT NULL, CONSTRAINT "UQ_f01b46ef789705fb6e134995f4e" UNIQUE ("center_code"), CONSTRAINT "PK_ef3dda6630851ce77a9fe7a0c9d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "languages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, CONSTRAINT "UQ_9c0e155475f0aa782e4a6178969" UNIQUE ("name"), CONSTRAINT "PK_b517f827ca496b29f4d549c631d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "towns" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "province_id" uuid, CONSTRAINT "UQ_2d2b2a755254e0c050ac4596bfb" UNIQUE ("name"), CONSTRAINT "PK_8f5c3dbce1d3ea5de7dcc48c230" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "provinces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, CONSTRAINT "UQ_5c78199072262966fb68b718095" UNIQUE ("name"), CONSTRAINT "PK_2e4260eedbcad036ec53222e0c7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "banks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "branch_code" character varying NOT NULL, CONSTRAINT "UQ_bbfa4b88c04b1bca7d7fc0f9261" UNIQUE ("branch_code"), CONSTRAINT "PK_3975b5f684ec241e3901db62d77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "first_name" character varying NOT NULL, "middle_name" character varying, "last_name" character varying NOT NULL, "date_of_birth" date NOT NULL, "address" jsonb NOT NULL, "gender" character varying NOT NULL DEFAULT 'female', "bank_account_number" character varying NOT NULL, "national_id_number" character varying NOT NULL, "mobile_number" character varying NOT NULL, "email_address" character varying, "proof_of_address" character varying NOT NULL, "national_id" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "blacklisted" boolean NOT NULL DEFAULT false, "office_id" uuid NOT NULL, "staff_id" uuid NOT NULL, "activated_by_id" uuid, "submitted_on" TIMESTAMP NOT NULL DEFAULT now(), "activated_on" TIMESTAMP, "audit_data" jsonb NOT NULL, "status_id" uuid NOT NULL, "province_id" uuid, "town_id" uuid, "language_id" uuid NOT NULL, "bank_id" uuid NOT NULL, "group_id" uuid, "center_id" uuid NOT NULL, CONSTRAINT "UQ_7f0755c27bf36220d55b7cf920b" UNIQUE ("bank_account_number"), CONSTRAINT "UQ_e7724425ea9164301e4bed68ec2" UNIQUE ("national_id_number"), CONSTRAINT "UQ_425d54cc04217430ef35a7587c7" UNIQUE ("mobile_number"), CONSTRAINT "UQ_14398a1329723622806c945ee06" UNIQUE ("email_address"), CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."loan_transactions_transaction_type_enum" AS ENUM('Disbursement', 'Repayment', 'Fee', 'Adjustment', 'Write-off')`);
        await queryRunner.query(`CREATE TYPE "public"."loan_transactions_payment_method_enum" AS ENUM('Cash', 'Bank Transfer', 'Mobile Money', 'Cheque')`);
        await queryRunner.query(`CREATE TABLE "loan_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "transaction_type" "public"."loan_transactions_transaction_type_enum" NOT NULL, "debit" numeric(12,2) NOT NULL, "credit" numeric(12,2) NOT NULL, "transaction_date" date NOT NULL, "payment_method" "public"."loan_transactions_payment_method_enum" NOT NULL, "receipt_number" character varying, "collected_by_id" uuid, "notes" character varying, "reversal_ref" character varying, "loan_id" uuid, "schedule_id" uuid, "reversal_transaction_id" uuid, "reversed_by_id" uuid, CONSTRAINT "UQ_b8aff149d23b9fb62fa45da31fe" UNIQUE ("receipt_number"), CONSTRAINT "PK_b0f7a6df01aa5f1627b765d9a1e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b8aff149d23b9fb62fa45da31f" ON "loan_transactions" ("receipt_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_4a2feffb768f5dd65393cba2c4" ON "loan_transactions" ("transaction_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_330d521c1e5502fafbedd779ba" ON "loan_transactions" ("loan_id") `);
        await queryRunner.query(`CREATE TYPE "public"."loan_schedule_status_enum" AS ENUM('Pending', 'Partially Paid', 'Paid', 'Overdue', 'Due')`);
        await queryRunner.query(`CREATE TABLE "loan_schedule" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "loan_id" uuid NOT NULL, "staff_id" uuid NOT NULL, "center_id" uuid NOT NULL, "office_id" uuid NOT NULL, "installment_number" integer NOT NULL, "due_date" date NOT NULL, "principal_due" numeric(12,2) NOT NULL, "interest_due" numeric(12,2) NOT NULL, "total_due" numeric(12,2) NOT NULL, "application_fee_due" numeric(12,2), "application_fee_paid" numeric(12,2), "service_fee_due" numeric(12,2), "principal_paid" numeric(12,2) NOT NULL DEFAULT '0', "interest_paid" numeric(12,2) NOT NULL DEFAULT '0', "penalty_paid" numeric(12,2) NOT NULL DEFAULT '0', "penalty_due" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."loan_schedule_status_enum", "paid_date" date, "service_fee_paid" numeric, "balance" numeric NOT NULL, "total_paid" numeric(12,2) NOT NULL DEFAULT '0', "group_package_id" uuid NOT NULL, CONSTRAINT "PK_23956fb5dc958396f8b4e2c9b6b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4d4fd526e8df3ea8a009e7594b" ON "loan_schedule" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_a93339bbd18978432384586be5" ON "loan_schedule" ("loan_id", "due_date") `);
        await queryRunner.query(`CREATE TYPE "public"."group_packages_status_enum" AS ENUM('Pending', 'Awaiting Disbursement', 'Active', 'Rejected', 'Completed')`);
        await queryRunner.query(`CREATE TABLE "group_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "group_id" uuid NOT NULL, "group_name" character varying NOT NULL, "user_id" uuid NOT NULL, "username" character varying NOT NULL, "status" "public"."group_packages_status_enum" NOT NULL DEFAULT 'Pending', "expected_disbursement_date" date NOT NULL, "approved_by" character varying, "amount" numeric NOT NULL DEFAULT '0', "total_expected_repayment" numeric NOT NULL DEFAULT '0', "repayment_dates" jsonb, "office_id" uuid NOT NULL, CONSTRAINT "PK_b86b108d4815d26998499c1cf31" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "loans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "client_id" uuid NOT NULL, "principal" integer NOT NULL, "total_interest" numeric NOT NULL, "interest_break_down" jsonb NOT NULL, "total_expected_repayment" numeric NOT NULL, "expected_disbursement_date" date NOT NULL, "number_of_repayments" integer NOT NULL, "loan_product_name" character varying NOT NULL, "staff_id" uuid NOT NULL, "user_name" character varying NOT NULL, "repayment_every" character varying NOT NULL, "expected_first_repayment_on_date" date NOT NULL, "timeline" jsonb NOT NULL, "repayments_due_dates" jsonb NOT NULL, "apr" numeric NOT NULL, "group_id" uuid, "group_name" character varying, "application_fee" numeric NOT NULL, "service_fee" integer NOT NULL, "installments" jsonb NOT NULL, "agreement_form" character varying, "disbursement_date" date, "disbursed_by_id" uuid, "disbursed_by_name" character varying, "first_approved_on" date, "first_approved_by_id" uuid, "first_approved_by_name" character varying, "second_approval_by_id" uuid, "second_approval_by_name" character varying, "second_approval_on_date" date, "can_be_used_for_top_up" boolean NOT NULL DEFAULT false, "office_id" uuid NOT NULL, "office_name" character varying NOT NULL, "in_arrears" boolean NOT NULL DEFAULT false, "is_written_off" boolean NOT NULL DEFAULT false, "status_id" character varying NOT NULL, "status" character varying NOT NULL, "arrears_start_date" date, "next_repayment_date" date, "audit_date" jsonb NOT NULL, "maximum_application_fee" numeric NOT NULL, "business_type" character varying, "group_package_id" uuid, "status_entity_id" uuid NOT NULL, CONSTRAINT "PK_5c6942c1e13e4de135c5203ee61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "offices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, "opening_date" TIMESTAMP NOT NULL DEFAULT now(), "parentId" uuid, CONSTRAINT "UQ_88aa5ebfe59f99cc747ca00f54f" UNIQUE ("name"), CONSTRAINT "PK_1ea41502c6dddcec44ad9fcbbb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('credit', 'branch_manager', 'loan_officer', 'regional_manager', 'super_user', 'finance', 'accounting', 'hr', 'it', 'marketing')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "first_name" character varying, "last_name" character varying, "email" character varying, "username" character varying NOT NULL, "password" character varying, "role" "public"."users_role_enum" NOT NULL, "phone" character varying, "office_id" uuid, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_a000cca60bcf04454e727699490" UNIQUE ("phone"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."audits_status_enum" AS ENUM('success', 'failed', 'error', 'pending', 'partial', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "audits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "auditable_type" character varying NOT NULL, "auditable_id" character varying NOT NULL, "event" character varying NOT NULL, "status" "public"."audits_status_enum" NOT NULL DEFAULT 'success', "old_values" jsonb, "new_values" jsonb, "user_id" character varying, "url" character varying, "ip_address" character varying, "user_agent" character varying, CONSTRAINT "PK_b2d7a2089999197dc7024820f28" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b3be7ec49dcb41083295ab9761" ON "audits" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_71dbdcdf7b96628ee77e50b6ca" ON "audits" ("event") `);
        await queryRunner.query(`CREATE INDEX "IDX_ada5e7e5604419d1e3ca08464b" ON "audits" ("user_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7cf76b0c43aa3219fe7bb6886" ON "audits" ("auditable_type", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_ce631103d4b166e645525cb7df" ON "audits" ("auditable_type", "auditable_id") `);
        await queryRunner.query(`CREATE TYPE "public"."loan_products_interest_method_enum" AS ENUM('flat', 'reducing_balance', 'compound')`);
        await queryRunner.query(`CREATE TYPE "public"."loan_products_term_unit_enum" AS ENUM('days', 'weeks', 'months', 'years')`);
        await queryRunner.query(`CREATE TABLE "loan_products" ("product_id" SERIAL NOT NULL, "product_name" character varying(100) NOT NULL, "interest_rate" numeric(10,2) NOT NULL, "interest_method" "public"."loan_products_interest_method_enum" NOT NULL, "min_amount" numeric(12,2), "max_amount" numeric(12,2), "term_min_months" integer, "term_max_months" integer, "late_fee" numeric(10,2), "grace_period_days" integer, "is_active" boolean, "term_length" integer, "term_unit" "public"."loan_products_term_unit_enum" DEFAULT 'months', CONSTRAINT "PK_b2bd08bda144cc871777a8216d4" PRIMARY KEY ("product_id"))`);
        await queryRunner.query(`CREATE TABLE "loan_table" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "term_length" integer, "term_unit" character varying(20), "loan_amount" integer NOT NULL, "application_fee" numeric(20,2) NOT NULL, "total_interest" numeric(20,8) NOT NULL, "service_fee" numeric(20,8) NOT NULL, "installment" integer NOT NULL, "maximum_application_fee" integer NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_9bd259f84b9cfbf02821bc272fc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "genders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "name" character varying NOT NULL, CONSTRAINT "UQ_4ff9b0934ba18fa74dd740b9adb" UNIQUE ("name"), CONSTRAINT "PK_529fb131dd4164c94529f53e19d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."chart_of_accounts_account_type_enum" AS ENUM('asset', 'liability', 'equity', 'income', 'expense', 'contra_asset')`);
        await queryRunner.query(`CREATE TABLE "chart_of_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "account_code" character varying(20) NOT NULL, "account_name" character varying(100) NOT NULL, "account_type" "public"."chart_of_accounts_account_type_enum" NOT NULL, "account_subtype" character varying(50), "parent_account_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "description" text, CONSTRAINT "UQ_1e09dc9479d5cac85e1a5bf9f8b" UNIQUE ("account_code"), CONSTRAINT "PK_467c08a2efc78393c647da32bac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "password_reset_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "expires_at" TIMESTAMP, "used" boolean NOT NULL DEFAULT false, "user_id" uuid, CONSTRAINT "PK_d16bebd73e844c48bca50ff8d3d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suspended_account_journals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "debit" numeric(12,2) NOT NULL, "credit" numeric(12,2) NOT NULL, "date" TIMESTAMP NOT NULL, "description" character varying NOT NULL, "status" character varying NOT NULL, CONSTRAINT "PK_f4c5ef69669206b59e0d7ca115b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suspense_accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "account_number" character varying NOT NULL, "account_name" character varying NOT NULL, "account_balance" integer NOT NULL, "account_status" character varying NOT NULL, "group_id" uuid NOT NULL, CONSTRAINT "UQ_1e461f75a64d63151a16508813b" UNIQUE ("group_id"), CONSTRAINT "PK_097be132813fa9e947ea3bb7ae2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."accruals_status_enum" AS ENUM('Pending', 'Posted', 'Reversed')`);
        await queryRunner.query(`CREATE TABLE "accruals" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "loan_id" uuid NOT NULL, "schedule_id" uuid NOT NULL, "accrual_date" date NOT NULL, "interest_accrued" numeric(12,2) NOT NULL, "penalty_accrued" numeric(12,2) NOT NULL DEFAULT '0', "status" "public"."accruals_status_enum" NOT NULL DEFAULT 'Pending', "gl_posted" boolean NOT NULL DEFAULT false, "gl_reference" character varying(20), CONSTRAINT "PK_55dd44da63eaaadd9c0226d9510" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ca09edcdac3bde82a559cdfb40" ON "accruals" ("accrual_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_3d52675a95b341aeac9990667c" ON "accruals" ("loan_id") `);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "debit"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "credit"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "collected_by_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversal_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversed_by_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "debit" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "credit" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "collected_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversal_transaction_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversed_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "amount" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "principal_amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "interest_amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "penalty_amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "fee_amount" numeric(12,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "collected_by" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ALTER COLUMN "loan_id" SET NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8aff149d23b9fb62fa45da31f"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "UQ_b8aff149d23b9fb62fa45da31fe"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "receipt_number"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "receipt_number" character varying(20)`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "UQ_b8aff149d23b9fb62fa45da31fe" UNIQUE ("receipt_number")`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversal_ref"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversal_ref" bigint`);
        await queryRunner.query(`CREATE INDEX "IDX_b8aff149d23b9fb62fa45da31f" ON "loan_transactions" ("receipt_number") `);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_67cacc6c07d079bc632b0cd8f81" FOREIGN KEY ("status_id") REFERENCES "statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_697c73a750a4c53f80a37cafa31" FOREIGN KEY ("group_leader_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_e167bff8d62d838874239c977d4" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_65a98f23825ecdcdaaeefe1da15" FOREIGN KEY ("created_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "groups" ADD CONSTRAINT "FK_31f0fdfc9ff7c89695bf0b63de8" FOREIGN KEY ("center_id") REFERENCES "center"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "center" ADD CONSTRAINT "FK_69770647a33f7b775d0ca93db9e" FOREIGN KEY ("meetingDateId") REFERENCES "center_meeting_dates"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "towns" ADD CONSTRAINT "FK_006bb683e0965b49557bbaea033" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_dbec8c45eb37b14f8d9846c35c3" FOREIGN KEY ("status_id") REFERENCES "statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_37ee346fbe749735f6b1b26e418" FOREIGN KEY ("province_id") REFERENCES "provinces"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_50357eb0e3ca9269f8f25f8b6d7" FOREIGN KEY ("town_id") REFERENCES "towns"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_a1d15f842a8317bf60d793823ea" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_2964262905a7e47429407b7282f" FOREIGN KEY ("bank_id") REFERENCES "banks"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_7a10e2319a4565e0308dd1d369c" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_d9fad5af157493cc4338ac4f5b3" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_9660d23297237c9eac3af096222" FOREIGN KEY ("activated_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_09e05215a309c4d7d8016ccfb91" FOREIGN KEY ("office_id") REFERENCES "offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_714b21411aea7467c6f866e2704" FOREIGN KEY ("center_id") REFERENCES "center"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_330d521c1e5502fafbedd779bab" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_c5d0bde69360c0485552e4b63a2" FOREIGN KEY ("schedule_id") REFERENCES "loan_schedule"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_9ca21a3b5c54953965d19e051c9" FOREIGN KEY ("collected_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_ae1426f764b5a28b4a36d02b6c7" FOREIGN KEY ("reversal_transaction_id") REFERENCES "loan_transactions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_d02dedfc8d435f881d82f7b0a48" FOREIGN KEY ("reversed_by_id") REFERENCES "loan_transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_schedule" ADD CONSTRAINT "FK_b818d2843a5da57013046a148ee" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_schedule" ADD CONSTRAINT "FK_7773821e4b94f37b6768bbe568c" FOREIGN KEY ("group_package_id") REFERENCES "group_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_packages" ADD CONSTRAINT "FK_85412593aa8160affce2accb020" FOREIGN KEY ("office_id") REFERENCES "offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "group_packages" ADD CONSTRAINT "FK_d9e6fae22598891654667956ced" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_e76d4de45737c4daf9719e2d0eb" FOREIGN KEY ("client_id") REFERENCES "clients"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_9d3434b023b37b6a2c5a271f119" FOREIGN KEY ("staff_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_db3de07bf0061a5d62ec08dcc85" FOREIGN KEY ("group_id") REFERENCES "groups"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_91e349583ab99ab941d30aade75" FOREIGN KEY ("disbursed_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_49f6f432f1853e8ede8c7c6d819" FOREIGN KEY ("first_approved_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_315538181d339d843f8cc091d8d" FOREIGN KEY ("second_approval_by_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_3e8a5dca55b0b016a09b5b7896b" FOREIGN KEY ("group_package_id") REFERENCES "group_packages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_83814f010ea77c7f6556443ee49" FOREIGN KEY ("office_id") REFERENCES "offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loans" ADD CONSTRAINT "FK_0a37da06c9d3b54f409e6986b70" FOREIGN KEY ("status_entity_id") REFERENCES "statuses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "offices" ADD CONSTRAINT "FK_fc1e71e57b3b710d91020765f1b" FOREIGN KEY ("parentId") REFERENCES "offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_6b31546fc92b0d7344f032d0447" FOREIGN KEY ("office_id") REFERENCES "offices"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "FK_9c45bac20a1578b010c5799ff34" FOREIGN KEY ("collected_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" ADD CONSTRAINT "FK_02bd780ff3e0e07fc414b4a9584" FOREIGN KEY ("parent_account_id") REFERENCES "chart_of_accounts"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" ADD CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accruals" ADD CONSTRAINT "FK_3d52675a95b341aeac9990667ce" FOREIGN KEY ("loan_id") REFERENCES "loans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accruals" ADD CONSTRAINT "FK_9bfbe917adf07e3c734ca5d369d" FOREIGN KEY ("schedule_id") REFERENCES "loan_schedule"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "accruals" DROP CONSTRAINT "FK_9bfbe917adf07e3c734ca5d369d"`);
        await queryRunner.query(`ALTER TABLE "accruals" DROP CONSTRAINT "FK_3d52675a95b341aeac9990667ce"`);
        await queryRunner.query(`ALTER TABLE "password_reset_tokens" DROP CONSTRAINT "FK_52ac39dd8a28730c63aeb428c9c"`);
        await queryRunner.query(`ALTER TABLE "chart_of_accounts" DROP CONSTRAINT "FK_02bd780ff3e0e07fc414b4a9584"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_9c45bac20a1578b010c5799ff34"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_6b31546fc92b0d7344f032d0447"`);
        await queryRunner.query(`ALTER TABLE "offices" DROP CONSTRAINT "FK_fc1e71e57b3b710d91020765f1b"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_0a37da06c9d3b54f409e6986b70"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_83814f010ea77c7f6556443ee49"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_3e8a5dca55b0b016a09b5b7896b"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_315538181d339d843f8cc091d8d"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_49f6f432f1853e8ede8c7c6d819"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_91e349583ab99ab941d30aade75"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_db3de07bf0061a5d62ec08dcc85"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_9d3434b023b37b6a2c5a271f119"`);
        await queryRunner.query(`ALTER TABLE "loans" DROP CONSTRAINT "FK_e76d4de45737c4daf9719e2d0eb"`);
        await queryRunner.query(`ALTER TABLE "group_packages" DROP CONSTRAINT "FK_d9e6fae22598891654667956ced"`);
        await queryRunner.query(`ALTER TABLE "group_packages" DROP CONSTRAINT "FK_85412593aa8160affce2accb020"`);
        await queryRunner.query(`ALTER TABLE "loan_schedule" DROP CONSTRAINT "FK_7773821e4b94f37b6768bbe568c"`);
        await queryRunner.query(`ALTER TABLE "loan_schedule" DROP CONSTRAINT "FK_b818d2843a5da57013046a148ee"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_d02dedfc8d435f881d82f7b0a48"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_ae1426f764b5a28b4a36d02b6c7"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_9ca21a3b5c54953965d19e051c9"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_c5d0bde69360c0485552e4b63a2"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "FK_330d521c1e5502fafbedd779bab"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_714b21411aea7467c6f866e2704"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_09e05215a309c4d7d8016ccfb91"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_9660d23297237c9eac3af096222"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_d9fad5af157493cc4338ac4f5b3"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_7a10e2319a4565e0308dd1d369c"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_2964262905a7e47429407b7282f"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_a1d15f842a8317bf60d793823ea"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_50357eb0e3ca9269f8f25f8b6d7"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_37ee346fbe749735f6b1b26e418"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_dbec8c45eb37b14f8d9846c35c3"`);
        await queryRunner.query(`ALTER TABLE "towns" DROP CONSTRAINT "FK_006bb683e0965b49557bbaea033"`);
        await queryRunner.query(`ALTER TABLE "center" DROP CONSTRAINT "FK_69770647a33f7b775d0ca93db9e"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_31f0fdfc9ff7c89695bf0b63de8"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_65a98f23825ecdcdaaeefe1da15"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_e167bff8d62d838874239c977d4"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_697c73a750a4c53f80a37cafa31"`);
        await queryRunner.query(`ALTER TABLE "groups" DROP CONSTRAINT "FK_67cacc6c07d079bc632b0cd8f81"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8aff149d23b9fb62fa45da31f"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversal_ref"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversal_ref" character varying`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "notes" character varying`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP CONSTRAINT "UQ_b8aff149d23b9fb62fa45da31fe"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "receipt_number"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "receipt_number" character varying`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD CONSTRAINT "UQ_b8aff149d23b9fb62fa45da31fe" UNIQUE ("receipt_number")`);
        await queryRunner.query(`CREATE INDEX "IDX_b8aff149d23b9fb62fa45da31f" ON "loan_transactions" ("receipt_number") `);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ALTER COLUMN "loan_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "collected_by"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "fee_amount"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "penalty_amount"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "interest_amount"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "principal_amount"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversed_by_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "reversal_transaction_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "collected_by_id"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "credit"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" DROP COLUMN "debit"`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversed_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "reversal_transaction_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "collected_by_id" uuid`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "credit" numeric(12,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "loan_transactions" ADD "debit" numeric(12,2) NOT NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3d52675a95b341aeac9990667c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ca09edcdac3bde82a559cdfb40"`);
        await queryRunner.query(`DROP TABLE "accruals"`);
        await queryRunner.query(`DROP TYPE "public"."accruals_status_enum"`);
        await queryRunner.query(`DROP TABLE "suspense_accounts"`);
        await queryRunner.query(`DROP TABLE "suspended_account_journals"`);
        await queryRunner.query(`DROP TABLE "password_reset_tokens"`);
        await queryRunner.query(`DROP TABLE "chart_of_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."chart_of_accounts_account_type_enum"`);
        await queryRunner.query(`DROP TABLE "genders"`);
        await queryRunner.query(`DROP TABLE "loan_table"`);
        await queryRunner.query(`DROP TABLE "loan_products"`);
        await queryRunner.query(`DROP TYPE "public"."loan_products_term_unit_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_products_interest_method_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ce631103d4b166e645525cb7df"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7cf76b0c43aa3219fe7bb6886"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ada5e7e5604419d1e3ca08464b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71dbdcdf7b96628ee77e50b6ca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b3be7ec49dcb41083295ab9761"`);
        await queryRunner.query(`DROP TABLE "audits"`);
        await queryRunner.query(`DROP TYPE "public"."audits_status_enum"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "offices"`);
        await queryRunner.query(`DROP TABLE "loans"`);
        await queryRunner.query(`DROP TABLE "group_packages"`);
        await queryRunner.query(`DROP TYPE "public"."group_packages_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a93339bbd18978432384586be5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4d4fd526e8df3ea8a009e7594b"`);
        await queryRunner.query(`DROP TABLE "loan_schedule"`);
        await queryRunner.query(`DROP TYPE "public"."loan_schedule_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_330d521c1e5502fafbedd779ba"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4a2feffb768f5dd65393cba2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b8aff149d23b9fb62fa45da31f"`);
        await queryRunner.query(`DROP TABLE "loan_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."loan_transactions_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."loan_transactions_transaction_type_enum"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TABLE "banks"`);
        await queryRunner.query(`DROP TABLE "provinces"`);
        await queryRunner.query(`DROP TABLE "towns"`);
        await queryRunner.query(`DROP TABLE "languages"`);
        await queryRunner.query(`DROP TABLE "center"`);
        await queryRunner.query(`DROP TABLE "groups"`);
        await queryRunner.query(`DROP TABLE "statuses"`);
        await queryRunner.query(`DROP TABLE "center_meeting_dates"`);
        await queryRunner.query(`DROP TYPE "public"."center_meeting_dates_day_enum"`);
        await queryRunner.query(`DROP TYPE "public"."center_meeting_dates_week_enum"`);
    }

}
